mygrep: mygrep.c mypattern.c myfilter.c extra_file.c
	gcc -o mygrep mygrep.c mypattern.c myfilter.c extra_file.c -I.

all: mygrep.c mypattern.c myfilter.c extra_file.c
	gcc -o mygrep mygrep.c mypattern.c myfilter.c extra_file.c -I.

clean :
	rm mygrep
